/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransporteRouteImport } from './routes/transporte'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RepresentantesRouteImport } from './routes/representantes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as NegociosRouteImport } from './routes/negocios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegociosIndexRouteImport } from './routes/negocios/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as NegociosIdRouteImport } from './routes/negocios/$id'
import { Route as LojaSlugRouteImport } from './routes/loja/$slug'
import { Route as AdminTransporteRouteImport } from './routes/admin/transporte'
import { Route as AdminServicosRouteImport } from './routes/admin/servicos'
import { Route as AdminRepresentantesRouteImport } from './routes/admin/representantes'
import { Route as AdminPlanosRouteImport } from './routes/admin/planos'
import { Route as AdminLojasRouteImport } from './routes/admin/lojas'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminDestaquesRouteImport } from './routes/admin/destaques'
import { Route as AdminCampanhasRouteImport } from './routes/admin/campanhas'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin/avaliacoes'
import { Route as AdminAprovacoesRouteImport } from './routes/admin/aprovacoes'

const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentantesRoute = RepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRoute = NegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIndexRoute = NegociosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NegociosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NegociosIdRoute = NegociosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NegociosRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransporteRoute = AdminTransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepresentantesRoute = AdminRepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestaquesRoute = AdminDestaquesRouteImport.update({
  id: '/destaques',
  path: '/destaques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAprovacoesRoute = AdminAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/negocios': typeof NegociosRouteWithChildren
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/representantes': typeof RepresentantesRoute
  '/servicos': typeof ServicosRoute
  '/transporte': typeof TransporteRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/transporte': typeof AdminTransporteRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/representantes': typeof RepresentantesRoute
  '/servicos': typeof ServicosRoute
  '/transporte': typeof TransporteRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/transporte': typeof AdminTransporteRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin': typeof AdminIndexRoute
  '/negocios': typeof NegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/negocios': typeof NegociosRouteWithChildren
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/representantes': typeof RepresentantesRoute
  '/servicos': typeof ServicosRoute
  '/transporte': typeof TransporteRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/destaques': typeof AdminDestaquesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/transporte': typeof AdminTransporteRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/negocios'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/representantes'
    | '/servicos'
    | '/transporte'
    | '/admin/aprovacoes'
    | '/admin/avaliacoes'
    | '/admin/campanhas'
    | '/admin/destaques'
    | '/admin/leads'
    | '/admin/lojas'
    | '/admin/planos'
    | '/admin/representantes'
    | '/admin/servicos'
    | '/admin/transporte'
    | '/loja/$slug'
    | '/negocios/$id'
    | '/admin/'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/representantes'
    | '/servicos'
    | '/transporte'
    | '/admin/aprovacoes'
    | '/admin/avaliacoes'
    | '/admin/campanhas'
    | '/admin/destaques'
    | '/admin/leads'
    | '/admin/lojas'
    | '/admin/planos'
    | '/admin/representantes'
    | '/admin/servicos'
    | '/admin/transporte'
    | '/loja/$slug'
    | '/negocios/$id'
    | '/admin'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anuncie'
    | '/cadastro'
    | '/como-funciona'
    | '/login'
    | '/negocios'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/representantes'
    | '/servicos'
    | '/transporte'
    | '/admin/aprovacoes'
    | '/admin/avaliacoes'
    | '/admin/campanhas'
    | '/admin/destaques'
    | '/admin/leads'
    | '/admin/lojas'
    | '/admin/planos'
    | '/admin/representantes'
    | '/admin/servicos'
    | '/admin/transporte'
    | '/loja/$slug'
    | '/negocios/$id'
    | '/admin/'
    | '/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LoginRoute: typeof LoginRoute
  NegociosRoute: typeof NegociosRouteWithChildren
  NoticiasRoute: typeof NoticiasRoute
  OfertasRoute: typeof OfertasRoute
  PerfilRoute: typeof PerfilRoute
  RepresentantesRoute: typeof RepresentantesRoute
  ServicosRoute: typeof ServicosRoute
  TransporteRoute: typeof TransporteRoute
  LojaSlugRoute: typeof LojaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representantes': {
      id: '/representantes'
      path: '/representantes'
      fullPath: '/representantes'
      preLoaderRoute: typeof RepresentantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios': {
      id: '/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof NegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/': {
      id: '/negocios/'
      path: '/'
      fullPath: '/negocios/'
      preLoaderRoute: typeof NegociosIndexRouteImport
      parentRoute: typeof NegociosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/negocios/$id': {
      id: '/negocios/$id'
      path: '/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof NegociosIdRouteImport
      parentRoute: typeof NegociosRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transporte': {
      id: '/admin/transporte'
      path: '/transporte'
      fullPath: '/admin/transporte'
      preLoaderRoute: typeof AdminTransporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/representantes': {
      id: '/admin/representantes'
      path: '/representantes'
      fullPath: '/admin/representantes'
      preLoaderRoute: typeof AdminRepresentantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destaques': {
      id: '/admin/destaques'
      path: '/destaques'
      fullPath: '/admin/destaques'
      preLoaderRoute: typeof AdminDestaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aprovacoes': {
      id: '/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AdminAprovacoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAprovacoesRoute: typeof AdminAprovacoesRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminDestaquesRoute: typeof AdminDestaquesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminRepresentantesRoute: typeof AdminRepresentantesRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminTransporteRoute: typeof AdminTransporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAprovacoesRoute: AdminAprovacoesRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminDestaquesRoute: AdminDestaquesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminRepresentantesRoute: AdminRepresentantesRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminTransporteRoute: AdminTransporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NegociosRouteChildren {
  NegociosIdRoute: typeof NegociosIdRoute
  NegociosIndexRoute: typeof NegociosIndexRoute
}

const NegociosRouteChildren: NegociosRouteChildren = {
  NegociosIdRoute: NegociosIdRoute,
  NegociosIndexRoute: NegociosIndexRoute,
}

const NegociosRouteWithChildren = NegociosRoute._addFileChildren(
  NegociosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  LoginRoute: LoginRoute,
  NegociosRoute: NegociosRouteWithChildren,
  NoticiasRoute: NoticiasRoute,
  OfertasRoute: OfertasRoute,
  PerfilRoute: PerfilRoute,
  RepresentantesRoute: RepresentantesRoute,
  ServicosRoute: ServicosRoute,
  TransporteRoute: TransporteRoute,
  LojaSlugRoute: LojaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
