/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PulsoRouteImport } from './routes/pulso'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as IaAssistenteRouteImport } from './routes/ia-assistente'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ConferirTudoRouteImport } from './routes/conferir-tudo'
import { Route as ClimaRouteImport } from './routes/clima'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegociosIndexRouteImport } from './routes/negocios/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as NegociosIdRouteImport } from './routes/negocios.$id'
import { Route as AdminPlanosRouteImport } from './routes/admin/planos'
import { Route as AdminLojasRouteImport } from './routes/admin/lojas'
import { Route as AdminAprovacoesRouteImport } from './routes/admin/aprovacoes'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PulsoRoute = PulsoRouteImport.update({
  id: '/pulso',
  path: '/pulso',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAssistenteRoute = IaAssistenteRouteImport.update({
  id: '/ia-assistente',
  path: '/ia-assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferirTudoRoute = ConferirTudoRouteImport.update({
  id: '/conferir-tudo',
  path: '/conferir-tudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimaRoute = ClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIndexRoute = NegociosIndexRouteImport.update({
  id: '/negocios/',
  path: '/negocios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NegociosIdRoute = NegociosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NegociosRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAprovacoesRoute = AdminAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/clima': typeof ClimaRoute
  '/conferir-tudo': typeof ConferirTudoRoute
  '/eventos': typeof EventosRoute
  '/ia-assistente': typeof IaAssistenteRoute
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/pulso': typeof PulsoRoute
  '/servicos': typeof ServicosRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clima': typeof ClimaRoute
  '/conferir-tudo': typeof ConferirTudoRoute
  '/eventos': typeof EventosRoute
  '/ia-assistente': typeof IaAssistenteRoute
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/pulso': typeof PulsoRoute
  '/servicos': typeof ServicosRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin': typeof AdminIndexRoute
  '/negocios': typeof NegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/clima': typeof ClimaRoute
  '/conferir-tudo': typeof ConferirTudoRoute
  '/eventos': typeof EventosRoute
  '/ia-assistente': typeof IaAssistenteRoute
  '/noticias': typeof NoticiasRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/pulso': typeof PulsoRoute
  '/servicos': typeof ServicosRoute
  '/admin/aprovacoes': typeof AdminAprovacoesRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/admin/': typeof AdminIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/clima'
    | '/conferir-tudo'
    | '/eventos'
    | '/ia-assistente'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/planos'
    | '/pulso'
    | '/servicos'
    | '/admin/aprovacoes'
    | '/admin/lojas'
    | '/admin/planos'
    | '/negocios/$id'
    | '/admin/'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/clima'
    | '/conferir-tudo'
    | '/eventos'
    | '/ia-assistente'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/planos'
    | '/pulso'
    | '/servicos'
    | '/admin/aprovacoes'
    | '/admin/lojas'
    | '/admin/planos'
    | '/negocios/$id'
    | '/admin'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/clima'
    | '/conferir-tudo'
    | '/eventos'
    | '/ia-assistente'
    | '/noticias'
    | '/ofertas'
    | '/perfil'
    | '/planos'
    | '/pulso'
    | '/servicos'
    | '/admin/aprovacoes'
    | '/admin/lojas'
    | '/admin/planos'
    | '/negocios/$id'
    | '/admin/'
    | '/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ClimaRoute: typeof ClimaRoute
  ConferirTudoRoute: typeof ConferirTudoRoute
  EventosRoute: typeof EventosRoute
  IaAssistenteRoute: typeof IaAssistenteRoute
  NoticiasRoute: typeof NoticiasRoute
  OfertasRoute: typeof OfertasRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PulsoRoute: typeof PulsoRoute
  ServicosRoute: typeof ServicosRoute
  NegociosIndexRoute: typeof NegociosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulso': {
      id: '/pulso'
      path: '/pulso'
      fullPath: '/pulso'
      preLoaderRoute: typeof PulsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-assistente': {
      id: '/ia-assistente'
      path: '/ia-assistente'
      fullPath: '/ia-assistente'
      preLoaderRoute: typeof IaAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferir-tudo': {
      id: '/conferir-tudo'
      path: '/conferir-tudo'
      fullPath: '/conferir-tudo'
      preLoaderRoute: typeof ConferirTudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clima': {
      id: '/clima'
      path: '/clima'
      fullPath: '/clima'
      preLoaderRoute: typeof ClimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/': {
      id: '/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof NegociosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/negocios/$id': {
      id: '/negocios/$id'
      path: '/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof NegociosIdRouteImport
      parentRoute: typeof NegociosRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aprovacoes': {
      id: '/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AdminAprovacoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAprovacoesRoute: typeof AdminAprovacoesRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAprovacoesRoute: AdminAprovacoesRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ClimaRoute: ClimaRoute,
  ConferirTudoRoute: ConferirTudoRoute,
  EventosRoute: EventosRoute,
  IaAssistenteRoute: IaAssistenteRoute,
  NoticiasRoute: NoticiasRoute,
  OfertasRoute: OfertasRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PulsoRoute: PulsoRoute,
  ServicosRoute: ServicosRoute,
  NegociosIndexRoute: NegociosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
